build:
    nodes:
        tests: true
        analysis:
            tests:
                override:
                    - php-scrutinizer-run
filter:
    excluded_paths:
        - "cs/"
        - "tests/"
tools:
    php_cs_fixer:
        config: { level: psr2 }
