build:
    nodes:
        compatibility:
            dependencies:
                override:
                    - composer update --prefer-dist --no-interaction --no-progress --optimize-autoloader
        tests: true
        analysis:
            tests:
                override:
                    - php-scrutinizer-run
filter:
    excluded_paths:
        - "cs/"
        - "tests/"
tools:
    php_cs_fixer:
        config: { level: psr2 }
