build:
    dependencies:
        override:
            - COMPOSER_ROOT_VERSION=dev-master composer update --prefer-dist --no-interaction --no-progress --optimize-autoloader
    nodes:
        analysis:
            tests:
                override:
                    - php-scrutinizer-run
filter:
    excluded_paths:
        - "tests/"
tools:
    php_cs_fixer:
        config: { level: psr2 }
