on:
  pull_request:
    paths-ignore:
      - 'README.md'
      - '.gitignore'
      - '.gitattributes'
      - 'psalm.xml'
      - 'phpunit.xml.dist'

  push:
    paths-ignore:
      - 'README.md'
      - '.gitignore'
      - '.gitattributes'
      - 'psalm.xml'
      - 'phpunit.xml.dist'

name: build

jobs:
  ci:
    uses: YiiRocks/.github/.github/workflows/ci.yml@main
    with:
      default-branch: master
