on:
  pull_request:
    paths-ignore:
      - 'README.md'
      - '.gitignore'
      - '.gitattributes'
      - 'psalm.xml'

  push:
    paths-ignore:
      - 'README.md'
      - '.gitignore'
      - '.gitattributes'
      - 'psalm.xml'

name: build

jobs:
  phpunit:
    uses: yiisoft/actions/.github/workflows/phpunit.yml@master
    with:
      os: >-
        ['ubuntu-latest', 'windows-latest']
      php: >-
        ['8.1', '8.2', '8.3', '8.4']
      extensions: 'fileinfo'
